name: effigy
description: An app which is used to store images and videos using gmail.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^1.17.1
  google_sign_in: ^5.3.3
  firebase_auth: ^3.3.19
  font_awesome_flutter: ^10.1.0
  provider: ^6.0.3
  google_fonts: ^3.0.1
  firebase_storage: ^10.2.17
  file_picker: ^3.0.4
  path: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
