name: effigy
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  # email_validator: ^2.0.1
  google_sign_in: ^5.3.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

assets:
  - assets/images/
