/// File generated by [ FlutterFire CLI ].

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  /// [ defaultPlatform ] is a method that returns the default platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }

    /// [ TargetPlatform.android ] is the default platform.
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      /// [ TargetPlatform.iOS ] is the default platform.
      case TargetPlatform.iOS:
        return ios;

      /// [ TargetPlatform.macOS ] is the default platform.
      case TargetPlatform.macOS:
        return macos;

      /// [ TargetPlatform.windows ] is the default platform.
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      /// [ TargetPlatform.linux ] is the default platform.
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      /// [ throw UnsupportedError ] if the platform is not supported.
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// [ android ] is a method that returns the default Firebase options for web.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSLXSer13gUGS3txgAVPF4rTuAIoBvv_8',
    appId: '1:229949727471:android:1b08d699cc09186001b11a',
    messagingSenderId: '229949727471',
    projectId: 'effigy-fluttervinu',
    storageBucket: 'effigy-fluttervinu.appspot.com',
  );

  /// [ ios ] is a method that returns the default Firebase options for android.

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBEjc_tKds7X7rjBez60PejauuZ_Tdo2g',
    appId: '1:229949727471:ios:ae53516fc285bbbe01b11a',
    messagingSenderId: '229949727471',
    projectId: 'effigy-fluttervinu',
    storageBucket: 'effigy-fluttervinu.appspot.com',
    androidClientId:
        '229949727471-34psjmugaab0n7i90pgngu1ge06ui4qo.apps.googleusercontent.com',
    iosClientId:
        '229949727471-riuqv8p60vqibj8e8e5h8f75e9o0q910.apps.googleusercontent.com',
    iosBundleId: 'com.example.effigy',
  );

  /// [ macos ] is a method that returns the default Firebase options for macos.

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBEjc_tKds7X7rjBez60PejauuZ_Tdo2g',
    appId: '1:229949727471:ios:ae53516fc285bbbe01b11a',
    messagingSenderId: '229949727471',
    projectId: 'effigy-fluttervinu',
    storageBucket: 'effigy-fluttervinu.appspot.com',
    androidClientId:
        '229949727471-34psjmugaab0n7i90pgngu1ge06ui4qo.apps.googleusercontent.com',
    iosClientId:
        '229949727471-riuqv8p60vqibj8e8e5h8f75e9o0q910.apps.googleusercontent.com',
    iosBundleId: 'com.example.effigy',
  );
}
