// File generated by FlutterFire CLI.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        return macos;

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCChltEwnoyI7NB27_W8YERHqcsyRTTDO4',
    appId: '1:229949727471:web:7efe9ab2a4ed644501b11a',
    messagingSenderId: '229949727471',
    projectId: 'effigy-fluttervinu',
    authDomain: 'effigy-fluttervinu.firebaseapp.com',
    storageBucket: 'effigy-fluttervinu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSLXSer13gUGS3txgAVPF4rTuAIoBvv_8',
    appId: '1:229949727471:android:9c6a2690e66b7c9501b11a',
    messagingSenderId: '229949727471',
    projectId: 'effigy-fluttervinu',
    storageBucket: 'effigy-fluttervinu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBEjc_tKds7X7rjBez60PejauuZ_Tdo2g',
    appId: '1:229949727471:ios:314db946f5859ed101b11a',
    messagingSenderId: '229949727471',
    projectId: 'effigy-fluttervinu',
    storageBucket: 'effigy-fluttervinu.appspot.com',
    iosClientId:
        '229949727471-riuqv8p60vqibj8e8e5h8f75e9o0q910.apps.googleusercontent.com',
    iosBundleId: 'com.example.effigy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBEjc_tKds7X7rjBez60PejauuZ_Tdo2g',
    appId: '1:229949727471:ios:314db946f5859ed101b11a',
    messagingSenderId: '229949727471',
    projectId: 'effigy-fluttervinu',
    storageBucket: 'effigy-fluttervinu.appspot.com',
    iosClientId:
        '229949727471-riuqv8p60vqibj8e8e5h8f75e9o0q910.apps.googleusercontent.com',
    iosBundleId: 'com.example.effigy',
  );
}
